
package org.example.service;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Server", targetNamespace = "http://example.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Server {


    /**
     * 
     */
    @WebMethod(operationName = "InitTestRecords")
    @RequestWrapper(localName = "InitTestRecords", targetNamespace = "http://example.org/", className = "org.example.service.InitTestRecords")
    @ResponseWrapper(localName = "InitTestRecordsResponse", targetNamespace = "http://example.org/", className = "org.example.service.InitTestRecordsResponse")
    @Action(input = "http://example.org/Server/InitTestRecordsRequest", output = "http://example.org/Server/InitTestRecordsResponse")
    public void initTestRecords();

    /**
     * 
     */
    @WebMethod(operationName = "PrintAllRecords")
    @RequestWrapper(localName = "PrintAllRecords", targetNamespace = "http://example.org/", className = "org.example.service.PrintAllRecords")
    @ResponseWrapper(localName = "PrintAllRecordsResponse", targetNamespace = "http://example.org/", className = "org.example.service.PrintAllRecordsResponse")
    @Action(input = "http://example.org/Server/PrintAllRecordsRequest", output = "http://example.org/Server/PrintAllRecordsResponse")
    public void printAllRecords();

    /**
     * 
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod(operationName = "AddMark")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "AddMark", targetNamespace = "http://example.org/", className = "org.example.service.AddMark")
    @ResponseWrapper(localName = "AddMarkResponse", targetNamespace = "http://example.org/", className = "org.example.service.AddMarkResponse")
    @Action(input = "http://example.org/Server/AddMarkRequest", output = "http://example.org/Server/AddMarkResponse")
    public int addMark(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     */
    @WebMethod(operationName = "AddFileToRecord")
    @RequestWrapper(localName = "AddFileToRecord", targetNamespace = "http://example.org/", className = "org.example.service.AddFileToRecord")
    @ResponseWrapper(localName = "AddFileToRecordResponse", targetNamespace = "http://example.org/", className = "org.example.service.AddFileToRecordResponse")
    @Action(input = "http://example.org/Server/AddFileToRecordRequest", output = "http://example.org/Server/AddFileToRecordResponse")
    public void addFileToRecord(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        byte[] arg2);

    /**
     * 
     * @param arg0
     */
    @WebMethod(operationName = "DeleteMark")
    @RequestWrapper(localName = "DeleteMark", targetNamespace = "http://example.org/", className = "org.example.service.DeleteMark")
    @ResponseWrapper(localName = "DeleteMarkResponse", targetNamespace = "http://example.org/", className = "org.example.service.DeleteMarkResponse")
    @Action(input = "http://example.org/Server/DeleteMarkRequest", output = "http://example.org/Server/DeleteMarkResponse")
    public void deleteMark(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns byte[]
     */
    @WebMethod(operationName = "GetFileFromRecord")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "GetFileFromRecord", targetNamespace = "http://example.org/", className = "org.example.service.GetFileFromRecord")
    @ResponseWrapper(localName = "GetFileFromRecordResponse", targetNamespace = "http://example.org/", className = "org.example.service.GetFileFromRecordResponse")
    @Action(input = "http://example.org/Server/GetFileFromRecordRequest", output = "http://example.org/Server/GetFileFromRecordResponse")
    public byte[] getFileFromRecord(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @return
     *     returns java.util.List<org.example.service.Record>
     */
    @WebMethod(operationName = "GetAllRecords")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "GetAllRecords", targetNamespace = "http://example.org/", className = "org.example.service.GetAllRecords")
    @ResponseWrapper(localName = "GetAllRecordsResponse", targetNamespace = "http://example.org/", className = "org.example.service.GetAllRecordsResponse")
    @Action(input = "http://example.org/Server/GetAllRecordsRequest", output = "http://example.org/Server/GetAllRecordsResponse")
    public List<Record> getAllRecords();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<org.example.service.Record>
     */
    @WebMethod(operationName = "GetRecordsByMark")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "GetRecordsByMark", targetNamespace = "http://example.org/", className = "org.example.service.GetRecordsByMark")
    @ResponseWrapper(localName = "GetRecordsByMarkResponse", targetNamespace = "http://example.org/", className = "org.example.service.GetRecordsByMarkResponse")
    @Action(input = "http://example.org/Server/GetRecordsByMarkRequest", output = "http://example.org/Server/GetRecordsByMarkResponse")
    public List<Record> getRecordsByMark(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     */
    @WebMethod(operationName = "AddMarksToRecord")
    @RequestWrapper(localName = "AddMarksToRecord", targetNamespace = "http://example.org/", className = "org.example.service.AddMarksToRecord")
    @ResponseWrapper(localName = "AddMarksToRecordResponse", targetNamespace = "http://example.org/", className = "org.example.service.AddMarksToRecordResponse")
    @Action(input = "http://example.org/Server/AddMarksToRecordRequest", output = "http://example.org/Server/AddMarksToRecordResponse")
    public void addMarksToRecord(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        List<Integer> arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod(operationName = "AddRecord")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "AddRecord", targetNamespace = "http://example.org/", className = "org.example.service.AddRecord")
    @ResponseWrapper(localName = "AddRecordResponse", targetNamespace = "http://example.org/", className = "org.example.service.AddRecordResponse")
    @Action(input = "http://example.org/Server/AddRecordRequest", output = "http://example.org/Server/AddRecordResponse")
    public int addRecord(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @return
     *     returns java.util.List<org.example.service.Mark>
     */
    @WebMethod(operationName = "GetAllMarks")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "GetAllMarks", targetNamespace = "http://example.org/", className = "org.example.service.GetAllMarks")
    @ResponseWrapper(localName = "GetAllMarksResponse", targetNamespace = "http://example.org/", className = "org.example.service.GetAllMarksResponse")
    @Action(input = "http://example.org/Server/GetAllMarksRequest", output = "http://example.org/Server/GetAllMarksResponse")
    public List<Mark> getAllMarks();

}
